### ISSUE TITLE
Pre-train Model

### ISSUE THREAD

**Issue by golnooshAbd** [NeurAI-Lab/biHomE#11]
Hi,
Is trained Model weights available to download?
Thanks in advance

**Comment by dkoguciuk** [comment]
Hi @golnooshAbd ,

Unfortunately, I am not able to share trained models, however, it is fairly easy to reproduce them. I suggest you use Zeng backbone + biHomE loss trained on the PDS-COCO dataset since this is the most robust configuration:

```
python3 train.py --config_file config/pds-coco/zeng-bihome-lr-1e-3.yaml
```

Best,
Daniel
