### ISSUE TITLE
model output

### ISSUE THREAD

**Issue by golnooshAbd** [NeurAI-Lab/biHomE#12]
Hi
Would you please explain outputs of model?
[https://github.com/NeurAI-Lab/biHomE/blob/main/train.py#L357](url)
What are delta_gt & delta_hat in train.py and eval.py? What is the difference?
How to train and inference this model on my own dataset?
Thanks in advanced.

**Comment by dkoguciuk** [comment]
Hi @golnooshAbd ,

> What are delta_gt & delta_hat in train.py and eval.py?

I am using a 4-point homography parametrization used by Detone[1] and introduced by Baker[2], so `delta_gt` is ground truth delta for all 4 corner points and `delta_hat` is predicted delta for those corners. It's more numerically stable to predict homography using this parametrization than predicting directly homography matrix.

> How to train and inference this model on my own dataset?

You would have to write your own dataset.py file, but it should also be really easy if you just copy existing dataset.py file (i.e. src/data/flir_adas/dataset.py) and modify it for your case. Please let me know if you have any further questions.

Best,
Daniel

[1] Daniel DeTone, Tomasz Malisiewicz, and Andrew Rabinovich. Deep Image Homography Estimation. arXiv preprint
arXiv:1606.03798, 2016
[2] Simon Baker, Ankur Datta, and Takeo Kanade. Parameterizing homographies. Technical Report CMU-RI-TR06-11, Robotics Institute, Pittsburgh, PA, March 2006.

**Comment by dkoguciuk** [comment]
Closing, feel free to reopen if  you have any other question.
