### ISSUE TITLE
Question abou the triplet loss you use?

### ISSUE THREAD

**Issue by DanilHu** [NeurAI-Lab/biHomE#13]
Hi, I have question about the triplet loss in your paper.
Here you said that the margin you use is infinite value, and you write the formulation as follow:
![image](https://user-images.githubusercontent.com/40864036/199141818-03babf9f-a357-4dfa-a638-28e1ce4070db.png)
I wonder whether the value of this loss can be negative? That means `ap_{i,j} < an_{i, j}` (or the distance between the anchor to positive sample is smaller the that between negative sample, and this seems easy to reach?) What does it mean when loss  is less than zero? how can it be optimized?

**Comment by dkoguciuk** [comment]
Hi @DanilHu ,

sorry for delay! See the answers below.

> I wonder whether the value of this loss can be negative?

Yes, it definitely can, and if you run  sample training it will get negative very quickly. 

> What does it mean when loss is less than zero? how can it be optimized?

It means exactly what you wrote, so the positive sample is more similar to the anchor than the negative sample and this is what we want. For the optimizer it doesn't matter if it's positive or negative, as soon as the loss landscape is smooth.

Best,
Daniel

**Comment by dkoguciuk** [comment]
Closing, feel free to reopen if you have any other questions.
