### ISSUE TITLE
The total loss is a negative value.

### ISSUE THREAD

**Issue by socome** [NeurAI-Lab/biHomE#6]
Thank you for your work and your contribution.

I have a question about the training process.

When I trained the model, the total loss is a negative value. 

![image](https://user-images.githubusercontent.com/44772344/151358298-401dccdd-e39e-4da6-8f36-efc4bd662805.png)

I didn't change anything and only use to following commands.

```
CUDA_VISIBLE_DEVICES=7 python train.py --config_file config/pds-coco/zhang-bihome-lr-1e-2.yaml
```

Do you have any idea about how to respond to this situation? 

![image](https://user-images.githubusercontent.com/44772344/151365566-e24774d5-6424-433d-8a30-8c0dc66872e7.png)

Also, Could you provide a config file about flir-adas..? @dkoguciuk

**Comment by socome** [comment]
My environment

![image](https://user-images.githubusercontent.com/44772344/151564144-6d67a591-1483-44ff-9a74-1f750cb53fb0.png)


ubuntu 18.04
torch 1.6.0
torchvision 0.7.0
kornia 0.5.0
colour-demosaicing 0.1.6
tensorboard 2.1.1

All of the requirements are installed.
The offline  data preparation process is done.

**Comment by dkoguciuk** [comment]
Hi @socome ,

thank you for interest in our work. Negative value of loss if expected here. In regression setting we penalize the network when prediction is far from expected: pixel offset (DeTone); or pixel color (Nguyen) -- and this difference cannot be negative. But here at the core of biHome method **is triplet loss with infinite margin** like stated in eq 11 in the paper: 

![Screenshot from 2022-01-31 22-37-11](https://user-images.githubusercontent.com/9368849/151877301-138d71cc-84c1-4c37-93f5-c5abbe70ec7b.png)

So, we hope that the distance between anchor and positive sample (ap) will be much smaller than between anchor and negative sample (an). 

All the best! May your gradients be finite and loss low,
Daniel

**Comment by socome** [comment]
Thank you for your reply.

Umm.. I’m still confused. From what I understand, you say “When the ap(distance between anchor and positive sample) is smaller than np(distance between anchor and negative sample), loss can be negative value” Right? 


I will try again..

**Comment by dkoguciuk** [comment]
Yes, exactly. But, please keep in mind that learning Zhang model is **very hard**. For 9 out of 10 models you will end up with non-converged model. To keep it simple, you could change `rho` to smaller value: go to `config/s-coco/zhang-bihome-lr-1e-2.yaml` and change the following:

```
  # Data transforms & args
  TRANSFORMS: [HomographyNetPrep: [32, 128, ['image_1', 'image_2'], 0, '4_points'],
               DictToGrayscale: [['patch_1', 'patch_2']],
               DictStandardize: [[0.443], [0.129], ['patch_1', 'patch_2']],
               DictToTensor: [['patch_1', 'patch_2']]]

  TEST_TRANSFORM: [HomographyNetPrep: [32, 128, ['image_1', 'image_2'], 0, '4_points'],
                   DictToGrayscale: [['patch_1', 'patch_2']],
                   DictStandardize: [[0.443], [0.129], ['patch_1', 'patch_2']],
                   DictToTensor: [['patch_1', 'patch_2']]]
```

into the following:

```
  # Data transforms & args
  TRANSFORMS: [HomographyNetPrep: [16, 128, ['image_1', 'image_2'], 0, '4_points'],
               DictToGrayscale: [['patch_1', 'patch_2']],
               DictStandardize: [[0.443], [0.129], ['patch_1', 'patch_2']],
               DictToTensor: [['patch_1', 'patch_2']]]

  TEST_TRANSFORM: [HomographyNetPrep: [16, 128, ['image_1', 'image_2'], 0, '4_points'],
                   DictToGrayscale: [['patch_1', 'patch_2']],
                   DictStandardize: [[0.443], [0.129], ['patch_1', 'patch_2']],
                   DictToTensor: [['patch_1', 'patch_2']]]
```

The first argument of HomographyNetPrep is `rho` and this model will be much easier to converge.
Best,
D

**Comment by socome** [comment]
Thank you a lot. I will try again!!
