### ISSUE TITLE
Some question about RANSAC

### ISSUE THREAD

**Issue by Acmenwangtuo** [NeurAI-Lab/biHomE#9]
Hello,in PFNet ,we should use ransac to sample point from PF, how u implement it , i use the kornia the cuda out of memory

**Comment by dkoguciuk** [comment]
Hi @Acmenwangtuo ,

exactly as you say, For training, we don't really need the real value of homography, so I only return `delta_hat` as a prediction of corner points of the image: https://github.com/NeurAI-Lab/biHomE/blob/main/src/heads/NoOpHead.py#L34

However, we need to use some method to find the homography out of the perspective field for testing, and here comes the RANSAC algorithm: https://github.com/NeurAI-Lab/biHomE/blob/main/src/heads/NoOpHead.py#L76

In general, the Zeng method takes much more GPU memory than other models implemented in this repo.

Best,
Daniel

**Comment by dkoguciuk** [comment]
Hi @Acmenwangtuo ,

I am closing the issue for now. Feel free to reopen if you'd like.

Best,
Daniel
